// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "fc410416-ea67-43a3-9543-62759c7ab544");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1580468769);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1580471091);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1580530678);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1580516518);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1580516398);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1580468607);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1580471331);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1580471211);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1580363480);
user_pref("browser.laterrun.bookkeeping.sessionCount", 10);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{578030b1-d908-465c-9e21-b02d90e67151}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1580457600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1580532979943");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1580534793943");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1580532981794");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1580536581794");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001400");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1580532979");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1580363511040");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "9ffd8577c65648c1ae5c0d305eb36b4c");
user_pref("extensions.blocklist.lastModified", "Tue, 28 Jan 2020 10:28:50 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1580468771);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001400");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"96a08225-7b28-40d9-b884-0c71a86b6a6c\",\"screenshots@mozilla.org\":\"cffce9c2-c3ab-44ba-839c-caf553b83463\",\"webcompat-reporter@mozilla.org\":\"74727d09-35f8-42ed-a9f0-ca109670a6b4\",\"webcompat@mozilla.org\":\"62166a8e-1365-49b4-a390-6447148b78ca\"}");
user_pref("idle.lastDailyNotification", 1580473459);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1580363520);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1580468368);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1580473459);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "70b8952f-a5e6-48fb-9a90-f5664f729444");
user_pref("security.sandbox.plugin.tempDirSuffix", "e3bbc688-c83d-421c-8ce1-fc232a731f84");
user_pref("services.blocklist.addons.checked", 1580463993);
user_pref("services.blocklist.gfx.checked", 1580463993);
user_pref("services.blocklist.onecrl.checked", 1580463993);
user_pref("services.blocklist.pinning.checked", 1580463993);
user_pref("services.blocklist.plugins.checked", 1580463993);
user_pref("services.settings.clock_skew_seconds", 4614);
user_pref("services.settings.last_update_seconds", 1580463993);
user_pref("services.settings.main.language-dictionaries.last_check", 1580463993);
user_pref("services.settings.main.sites-classification.last_check", 1580463993);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1580473459);
user_pref("toolkit.startup.last_success", 1580532973);
user_pref("toolkit.telemetry.cachedClientID", "07489a3a-0ae5-4ba2-8c31-8911dd908aaf");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
